baseURL: "https://www.amancloud.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "AmanCloud"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "AmanCloud"
  description: "We specialize in providing services to support solution design, build and management for customers."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  # social:
  #   dribbble: "#"
  #   instagram: "#"
  #   facebook: "#"
  #   twitter: "#"

  location:
    - "3, Jalan 1/2a, Seksyen 1, 43650 Bandar Baru Bangi, Selangor 43650"

  contact:
    - "rahman@amancloud.com"
    - "60.16.6157156"

  copyright: "© 2024 AmanCloud All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  buttons:
    - name: "Book a call"
      url: "https://wa.me/message/HDGICETLC5W4N1"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "How we work"
    #   url: "/#"
    #   weight: 2

    # - name: "Our team"
    #   url: "/#"
    #   weight: 3

    # - name: "Pricing"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"